/// <reference types="@types/chrome" />

import type Browser from 'webextension-polyfill'
import type { DeepAssign, DeepOverwrite } from './types/utils'

declare global {
  namespace chrome {
    namespace runtime {
      function getManifest(): ManifestV3 & Browser.Manifest.WebExtensionManifest
    }
  }
}

// Generated by wxt
interface ImportMetaEnv {
  readonly BROWSER: 'chrome' | 'firefox' | 'safari' | 'edge' | 'opera'
}

declare class ServiceWorkerGlobalScope {}

interface OpenPopoutCreateData
  extends Omit<chrome.windows.CreateData, 'type' | 'url'> {}

interface WebExtBase extends DeepAssign<typeof chrome, Browser.Browser> {}

interface WebExtOverride {
  action: {
    path?: string

    openPopout(
      createData: OpenPopoutCreateData
    ): Promise<chrome.windows.Window | undefined>
  }

  sidePanel: {
    path?: string

    openPopout(
      createData: OpenPopoutCreateData
    ): Promise<chrome.windows.Window | undefined>
  }

  tabs: {
    getCurrentActive(): Promise<chrome.tabs.Tab | undefined>
    getCurrentActiveId(): Promise<number | undefined>
  }
}

interface WebExt extends DeepOverwrite<WebExtBase, WebExtOverride> {
  context: {
    LINKED_TAB_ID_NAME: string

    /**
     * ブラウザ
     */
    browser: ImportMetaEnv['BROWSER']
    /**
     * 実行場所
     */
    type: 'background' | 'content-script' | 'popup' | 'sidepanel' | null
    /**
     * リンクされたタブID
     */
    linkedTabId: number
    /**
     * ポップアウトかどうか
     */
    isPopout: boolean
  }
}

export const webext = (globalThis.browser?.runtime?.id
  ? globalThis.browser
  : globalThis.chrome) as unknown as WebExt

const manifest = webext.runtime.getManifest()

const env = import.meta.env as unknown as ImportMetaEnv

webext.context = {
  LINKED_TAB_ID_NAME: '_webext_linked_tab_id',

  browser: env.BROWSER,
  type: null,
  linkedTabId: -1,
  isPopout: false,
}

// 実行場所
if (
  // Chrome
  (typeof ServiceWorkerGlobalScope !== 'undefined' &&
    self instanceof ServiceWorkerGlobalScope) ||
  // Firefox
  (typeof window !== 'undefined' &&
    webext.extension?.getBackgroundPage?.() === window)
) {
  // バックグラウンド
  webext.context.type = 'background'
} else if (/^https?:$/.test(location.protocol)) {
  // コンテンツスクリプト
  webext.context.type = 'content-script'
} else if (location.pathname === '/popup.html') {
  // ポップアップ
  webext.context.type = 'popup'
} else if (location.pathname === '/sidepanel.html') {
  // サイドパネル
  webext.context.type = 'sidepanel'
}

// リンクされたタブID
webext.context.linkedTabId = Number(
  new URLSearchParams(location.search).get(webext.context.LINKED_TAB_ID_NAME) ||
    -1
)

// ポップアウトかどうか
webext.context.isPopout = webext.tabs.TAB_ID_NONE < webext.context.linkedTabId

if (webext.tabs) {
  webext.tabs.getCurrentActive = async function () {
    try {
      const tab =
        webext.context.linkedTabId !== null
          ? await this.get(webext.context.linkedTabId)
          : (await this.query({ active: true, currentWindow: true }))[0]

      if (tab?.id != null && tab.id !== this.TAB_ID_NONE) {
        return tab
      }
    } catch {}
  }
  webext.tabs.getCurrentActiveId = async function () {
    const tab = await this.getCurrentActive()

    return tab?.id
  }
}

async function openPopout(
  this: WebExt['action'] | WebExt['sidePanel'],
  { tabId, ...createData }: OpenPopoutCreateData
): Promise<chrome.windows.Window | undefined> {
  if (tabId == null || tabId === webext.tabs.TAB_ID_NONE) {
    tabId = await webext.tabs.getCurrentActiveId()
  }

  const url =
    tabId != null && tabId !== webext.tabs.TAB_ID_NONE
      ? `${this.path}?${webext.context.LINKED_TAB_ID_NAME}=${tabId}`
      : this.path

  return webext.windows.create({
    ...createData,
    type: 'popup',
    url,
  })
}

if (webext.action) {
  webext.action.path = manifest.action?.default_popup

  webext.action.openPopout = openPopout
}

switch (webext.context.browser) {
  // Chrome
  case 'chrome':
  case 'edge':
  case 'opera': {
    if (webext.sidePanel) {
      webext.sidePanel.path = manifest.side_panel?.default_path

      webext.sidePanel.open = new Proxy(webext.sidePanel.open, {
        async apply(
          target,
          thisArg: typeof chrome.sidePanel,
          [options]: Parameters<typeof chrome.sidePanel.open>
        ) {
          if (options?.tabId == null) {
            const tabId = await webext.tabs.getCurrentActiveId()

            if (tabId != null) {
              if (options) {
                options.tabId = tabId
              } else {
                options = { tabId }
              }
            }
          }

          await thisArg.setOptions({
            enabled: true,
            path: webext.sidePanel.path,
            tabId: options?.tabId,
          })

          return Reflect.apply(target, thisArg, [options])
        },
      })

      webext.sidePanel.close = async function (options) {
        if (options?.tabId == null) {
          const tabId = await webext.tabs.getCurrentActiveId()

          if (tabId != null) {
            if (options) {
              options.tabId = tabId
            } else {
              options = { tabId }
            }
          }
        }

        return this.setOptions({
          enabled: false,
          tabId: options?.tabId,
        })
      }

      webext.sidePanel.openPopout = openPopout
    }
  }

  // Firefox
  case 'firefox': {
    webext.storage.local.getBytesInUse = async function (keys) {
      const values = await this.get(keys as any)

      return Object.entries(values).reduce((prev, [key, value]) => {
        const { size } = new Blob([
          key,
          typeof value === 'string' ? value : JSON.stringify(value),
        ])

        return prev + size
      }, 0)
    }

    if (webext.sidebarAction) {
      enum Side {
        LEFT = 'left',
        RIGHT = 'right',
      }

      webext.sidePanel = {
        Side,

        path: manifest.sidebar_action?.default_panel,

        open() {
          return webext.sidebarAction.open()
        },

        close() {
          return webext.sidebarAction.close()
        },

        openPopout,

        async getOptions(options) {
          const { tabId } = options ?? {}

          let isOpen = false

          if (tabId != null) {
            const { windowId } = await webext.tabs.get(tabId)

            isOpen = await webext.sidebarAction.isOpen({ windowId })
          }

          const path = this.path
          const enabled = !!path && isOpen

          return { enabled, path, tabId }
        },

        async setOptions({ enabled, path, tabId }) {
          const panel = enabled ? path || this.path || null : null

          await webext.sidebarAction.setPanel({ panel, tabId })
        },

        async getPanelBehavior() {
          return {}
        },

        async setPanelBehavior() {},

        async getLayout() {
          return {
            side: this.Side.RIGHT,
          }
        },

        onOpened: {
          addListener() {},
          getRules() {},
          hasListener() {
            return false
          },
          removeRules() {},
          addRules() {},
          removeListener() {},
          hasListeners() {
            return false
          },
        },

        onClosed: {
          addListener() {},
          getRules() {},
          hasListener() {
            return false
          },
          removeRules() {},
          addRules() {},
          removeListener() {},
          hasListeners() {
            return false
          },
        },
      }
    }
  }
}
